spring:
  application:
    name: keycloak
  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: keycloak
            client-secret: zBse6Urlt3JkLzd6TG5nUuvJmosmrMwR
            redirect-uri: "http://localhost:8081/login/oauth2/code/keycloak"
            scope: openid,profile,email

        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/api-realm

server:
  port: 8081



